name: Publish to Medium

on:
  push:
    branches:
      - main

env:
  MEDIUM_API_KEY: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker://pandoc/core:2.11

    - name: Convert markdown to HTML
      run: |
        pandoc input.md -f markdown -t html -s -o output.html

    - name: Publish to Medium
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $MEDIUM_INTEGRATION_TOKEN" \
        -d "{\"title\":\"My blog post\",\"contentFormat\":\"html\",\"content\":\"$(cat output.html)\",\"publishStatus\":\"public\"}" \
        https://api.medium.com/v1/posts
