name: Publish Markdown to Medium

on:
  push:
    branches:
      - main

env:
  MEDIUM_INTEGRATION_TOKEN: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pandoc
      run: apk add --no-cache pandoc

    - name: Convert Markdown to HTML
      run: pandoc --from=markdown --to=html file.md -o file.html

    - name: Publish to Medium
      uses: medium/actions/publish@v1
      with:
        integrationToken: ${{ env.MEDIUM_INTEGRATION_TOKEN }}
        title: "My New Story"
        contentFormat: html
        content: ${{ steps.convert.outputs.html }}
        tags: "github, medium, markdown"
        canonicalUrl: "https://github.com/<OWNER>/<REPO>/blob/<BRANCH>/file.md"
        publishStatus: draft
        
